'use strict';
const $=s=>document.querySelector(s);
const restoredConversation=new URLSearchParams(location.hash.slice(1)).get('conversation');
const token=new URLSearchParams(location.hash.slice(1)).get('token')||sessionStorage.getItem('kel-token');
if(token){sessionStorage.setItem('kel-token',token);history.replaceState(null,'',location.pathname);}
let conversation=restoredConversation||localStorage.getItem('kel-conversation')||'main',currentProject='default',state=null,pending=[],editingProject=null,busy=false,lastRender='',lastNav='';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,data){const r=await fetch(path,{method:data===undefined?'GET':'POST',headers:{'Authorization':'Bearer '+token,...(data===undefined?{}:{'Content-Type':'application/json'})},body:data===undefined?undefined:JSON.stringify(data)});const type=r.headers.get('Content-Type')||'';const value=type.includes('application/json')?await r.json():await r.text();if(!r.ok)throw Error(value.error||'Request failed');return value;}
function alertUser(message){$('#alerts').textContent=message;$('#alerts').classList.toggle('error',!!message);}
function markdown(text){
 const inline=s=>esc(s).replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>');
 let html=[],paragraph=[],code=[],fenced=false;
 const flush=()=>{if(paragraph.length){html.push('<p>'+paragraph.map(inline).join('<br>')+'</p>');paragraph=[];}};
 for(const line of String(text).split('\n')){
  if(line.startsWith('```')){flush();if(fenced){html.push('<pre tabindex="0"><code>'+esc(code.join('\n'))+'</code></pre>');code=[];}fenced=!fenced;continue;}
  if(fenced){code.push(line);continue;}
  const heading=line.match(/^(#{1,3})\s+(.+)$/);
  if(heading){flush();const level=heading[1].length;html.push('<h'+level+'>'+inline(heading[2])+'</h'+level+'>');}
  else if(!line.trim()){flush();}else paragraph.push(line);
 }
 flush();if(code.length)html.push('<pre tabindex="0"><code>'+esc(code.join('\n'))+'</code></pre>');return html.join('');
}
function timeLabel(timestamp){return new Date(timestamp*1000).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});}
function jobLabel(job){const states=Object.values(job.milestones).map(m=>m.state);if(job.state==='AWAITING_USER')return 'Needs your permission';if(job.state==='PAUSED')return 'Paused';if(job.state==='WAITING_RESOURCE')return 'Waiting for a worker';if(job.state==='CANCELLING'||job.state==='PAUSING')return 'Stopping work';if(states.includes('CHECKING')||states.includes('UNCERTAIN'))return 'Checking the result';if(states.includes('NEEDS_REPAIR'))return 'Repairing a failed check';return 'Working';}
function render(){if(!state)return;const selected=state.conversations.find(c=>c.id===conversation);currentProject=selected?.project_id||currentProject;$('#conversation-title').textContent=selected?.title||'New conversation';const navKey=JSON.stringify([state.projects,state.conversations,conversation,currentProject]);if(navKey!==lastNav){lastNav=navKey;$('#projects').innerHTML=state.projects.map(p=>'<option value="'+esc(p.id)+'">'+esc(p.name)+'</option>').join('');$('#projects').value=currentProject;$('#conversations').innerHTML=state.conversations.filter(c=>c.project_id===currentProject).map(c=>'<button data-conversation="'+esc(c.id)+'" class="'+(c.id===conversation?'selected':'')+'">'+esc(c.title)+'</button>').join('');}
 const key=JSON.stringify([state.messages.map(m=>[m.seq,m.text]),state.jobs.map(j=>[j.id,j.state,j.verdict,Object.values(j.milestones).map(m=>[m.state,m.attempts,m.artifact?.sha256])]),state.approvals,state.submissions.map(s=>[s.id,s.state,s.error])]);
 if(key!==lastRender){lastRender=key;const pane=$('#journal'),nearBottom=pane.scrollHeight-pane.scrollTop-pane.clientHeight<100;const oldScroll=pane.scrollTop;let html='',day='';for(const message of state.messages){const date=new Date(message.at*1000).toLocaleDateString([],{weekday:'long',month:'long',day:'numeric'});if(date!==day){day=date;html+='<div class="date">'+esc(date)+'</div>';}html+='<section class="entry '+esc(message.role)+'"><div class="stamp">'+(message.role==='user'?'You':'Kel')+' · '+timeLabel(message.at)+'</div><div class="message-body">'+(message.role==='user'?esc(message.text):markdown(message.text))+'</div>';const job=state.jobs.find(j=>j.id===message.job_id);if(message.role==='assistant'&&job?.verdict==='VERIFIED'){for(const [mid,m] of Object.entries(job.milestones)){if(m.state!=='ACCEPTED'||(job.contract.final_milestone&&mid!==job.contract.final_milestone))continue;const spec=job.contract.milestones.find(s=>s.id===mid);html+='<button class="file-button" data-download-job="'+esc(job.id)+'" data-milestone="'+esc(mid)+'" data-name="'+esc(spec.filename)+'">↓ '+esc(spec.filename)+'</button>';}if(job.contract.kind==='coding')html+='<button class="file-button" data-apply-job="'+esc(job.id)+'" title="'+esc(job.contract.root)+'">Apply checked changes</button>';}if(message.role==='user'&&job?.contract.context?.files){for(const f of job.contract.context.files)html+='<div class="file-button">Attached: '+esc(f.name)+'</div>';}html+='</section>';}
 for(const a of state.approvals){if(!state.jobs.some(j=>j.id===a.job_id))continue;const action=JSON.parse(a.action);html+='<section class="entry assistant permission"><h3>Allow this action?</h3><p>Kel needs permission before continuing this task.</p><pre>'+esc(action.command||JSON.stringify(action.changes||action.permissions||{folder:action.grantRoot},null,2))+'\n'+esc(action.workspace||'')+'</pre><label><input type="checkbox" data-remember="'+esc(a.id)+'"> Remember this exact action for this project for one day</label><div class="actions"><button class="primary" data-approval="'+esc(a.id)+'" data-allow="true">Allow</button><button class="outlined" data-approval="'+esc(a.id)+'" data-allow="false">Deny</button></div></section>';}
 for(const s of state.submissions.filter(s=>['FAILED','INTERRUPTED'].includes(s.state)))html+='<section class="entry assistant"><div class="stamp">Kel</div><p class="error">'+esc(s.error)+'</p><button class="outlined" data-retry="'+esc(s.id)+'">Retry request</button></section>';
 pane.innerHTML=html||'<div class="empty"><p>Your work, in order</p><h1>What would you like to work on?</h1><p>Send a request. Add files or project context when they help.</p></div>';if(nearBottom)pane.scrollTop=pane.scrollHeight;else pane.scrollTop=oldScroll;
 }
 let work='';for(const s of state.submissions.filter(s=>s.state==='PLANNING'))work+='<div class="work-line"><span>Understanding your request…</span></div>';for(const j of state.jobs.filter(j=>!['CLOSED','CANCELLED'].includes(j.state))){const accepted=Object.values(j.milestones).filter(m=>m.state==='ACCEPTED').length;work+='<div class="work-line"><span>'+esc(jobLabel(j))+' · '+accepted+' of '+Object.keys(j.milestones).length+' steps checked</span>'+(j.state==='PAUSED'?'<button data-control="resume" data-job="'+esc(j.id)+'">Resume</button>':'<button data-control="pause" data-job="'+esc(j.id)+'">Stop</button>')+'</div>';}
 if($('#work-status').innerHTML!==work)$('#work-status').innerHTML=work;$('#connection').textContent='Running on this computer';filterConversations();if(state.error)alertUser(state.error);
}
async function refresh(){try{state=await api('/api/state?conversation='+encodeURIComponent(conversation));if(!state.conversations.some(c=>c.id===conversation)){conversation='main';localStorage.setItem('kel-conversation',conversation);lastRender='';return refresh();}render();}catch(e){$('#connection').textContent='Connection lost';alertUser('Kel is not connected. Your saved work stays on this computer. '+e.message);}}
async function selectConversation(id){conversation=id;localStorage.setItem('kel-conversation',id);await window.kelDesktop?.saveConversation(id);lastRender='';pending=[];renderPending();document.body.classList.remove('nav-open');await refresh();$('#journal').scrollTop=$('#journal').scrollHeight;$('#message').focus();}
async function newConversation(){busy=true;$('#send').disabled=true;try{const r=await api('/api/conversation',{project:currentProject});await selectConversation(r.id);}finally{busy=false;$('#send').disabled=false;}}
function renderPending(){$('#pending-files').innerHTML=pending.map((f,i)=>'<span class="pending-file">'+esc(f.name)+'<button type="button" data-remove-file="'+i+'" aria-label="Remove '+esc(f.name)+'">×</button></span>').join('');}
$('#composer').addEventListener('submit',async e=>{e.preventDefault();const text=$('#message').value.trim();if(!text||busy)return;busy=true;$('#send').disabled=true;alertUser('');try{await api('/api/send',{id:crypto.randomUUID(),conversation,text,attachments:pending.map(f=>f.id)});$('#message').value='';pending=[];renderPending();await refresh();$('#journal').scrollTop=$('#journal').scrollHeight;}catch(error){alertUser(error.message);}finally{busy=false;$('#send').disabled=false;$('#message').focus();}});
$('#message').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();$('#composer').requestSubmit();}});
$('#attach').onclick=()=>$('#file').click();$('#file').onchange=async e=>{try{for(const file of e.target.files){if(file.size>5000000)throw Error('Files must be 5 MB or smaller.');const base64=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file);});const result=await api('/api/attach',{conversation,name:file.name,mime:file.type||'text/plain',content:base64});pending.push({id:result.id,name:file.name});}renderPending();alertUser('');}catch(error){alertUser(error.message);}finally{$('#file').value='';}};
$('#new-chat').onclick=()=>newConversation().catch(e=>alertUser(e.message));$('#menu').onclick=()=>document.body.classList.toggle('nav-open');
$('#projects').onchange=async e=>{currentProject=e.target.value;const existing=state.conversations.find(c=>c.project_id===currentProject);try{if(existing)await selectConversation(existing.id);else await newConversation();}catch(error){alertUser(error.message);}};
function openProject(isNew=false){$('#project-error').textContent='';editingProject=isNew?null:state.projects.find(p=>p.id===currentProject);$('#project-name').value=editingProject?.name||'';$('#project-root').value=editingProject?.root||'';$('#project-notes').value=editingProject?.context||'';$('#test-command').value=editingProject?.test_command?JSON.stringify(editingProject.test_command):'';$('#project-dialog').showModal();$('#project-name').focus();}
$('#project-context').onclick=()=>openProject();$('#new-project').onclick=()=>openProject(true);$('#project-form').onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;$('#send').disabled=true;const save=e.submitter;if(save)save.disabled=true;try{const command=$('#test-command').value.trim();const isNew=!editingProject;const result=await api('/api/project',{id:editingProject?.id,name:$('#project-name').value,root:$('#project-root').value,context:$('#project-notes').value,test_command:command?JSON.parse(command):null});await refresh();currentProject=result.id;if(isNew){const created=await api('/api/conversation',{project:result.id});await selectConversation(created.id);}else await refresh();$('#project-dialog').close();}catch(error){$('#project-error').textContent=error.message;}finally{busy=false;$('#send').disabled=false;if(save)save.disabled=false;}};
$('#browse-folder').onclick=async()=>{if(window.kelDesktop){const path=await window.kelDesktop.chooseFolder();if(path)$('#project-root').value=path;}else{$('#project-root').focus();alertUser('Enter the local project folder path. The desktop app also offers a folder picker.');}};
$('#revoke').onclick=async()=>{try{await api('/api/revoke',{project:currentProject});alertUser('Saved permissions cleared.');}catch(e){alertUser(e.message);}};
$('#details').onclick=()=>{$('#work-content').innerHTML=state.jobs.length?state.jobs.map(j=>'<section><h3>'+esc(j.contract.request)+'</h3><p>'+esc(j.state)+' · '+esc(j.verdict)+'</p>'+Object.entries(j.milestones).map(([id,m])=>'<p>'+esc(id)+': '+esc(m.state)+' · '+m.attempts+' attempt(s)</p><pre>'+esc(m.error||JSON.stringify(m.checks,null,2))+'</pre>').join('')+'</section>').join(''):'<p>No saved work in this conversation.</p>';$('#work-dialog').showModal();};
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{if(b.dataset.close)$('#'+b.dataset.close).close();if(b.dataset.conversation)await selectConversation(b.dataset.conversation);if(b.dataset.removeFile!==undefined){pending.splice(Number(b.dataset.removeFile),1);renderPending();}if(b.dataset.applyJob){b.disabled=true;try{const result=await api('/api/apply',{job:b.dataset.applyJob});alertUser(result.already_applied?'These changes were already applied.':'Checked changes applied. A backup was saved.');}finally{b.disabled=false;}}if(b.dataset.control){await api('/api/control',{job:b.dataset.job,action:b.dataset.control});await refresh();}if(b.dataset.approval){const remember=document.querySelector('[data-remember="'+CSS.escape(b.dataset.approval)+'"]')?.checked;await api('/api/approval',{id:b.dataset.approval,allow:b.dataset.allow==='true',remember});await refresh();}if(b.dataset.retry){await api('/api/retry',{id:b.dataset.retry});await refresh();}if(b.dataset.downloadJob){const text=await api('/api/artifact?job='+encodeURIComponent(b.dataset.downloadJob)+'&milestone='+encodeURIComponent(b.dataset.milestone));const url=URL.createObjectURL(new Blob([text],{type:'text/markdown'}));const link=document.createElement('a');link.href=url;link.download=b.dataset.name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}catch(error){alertUser(error.message);}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!document.querySelector('dialog[open]')&&document.body.classList.contains('nav-open')){document.body.classList.remove('nav-open');syncSidebar();$('#menu').focus();}});
refresh();setInterval(refresh,1000);


function syncSidebar(){const narrow=matchMedia('(max-width:900px)').matches;const open=document.body.classList.contains('nav-open');$('#sidebar').inert=narrow&&!open;$('.main-shell').inert=narrow&&open;}
new MutationObserver(syncSidebar).observe(document.body,{attributes:true,attributeFilter:['class']});
matchMedia('(max-width:900px)').addEventListener('change',syncSidebar);
$('#close-sidebar').onclick=()=>{document.body.classList.remove('nav-open');syncSidebar();$('#menu').focus();};
$('#menu').onclick=()=>{document.body.classList.toggle('nav-open');syncSidebar();if(document.body.classList.contains('nav-open'))$('#close-sidebar').focus();};
syncSidebar();

function filterConversations(){const q=$('#search-chats').value.trim().toLowerCase();for(const b of $('#conversations').querySelectorAll('button'))b.hidden=!!q&&!b.textContent.toLowerCase().includes(q);}
$('#search-chats').addEventListener('input',filterConversations);
let previewItem=null,previewText='',previewMode='rendered',previewRequest=0;
function renderPreview(){
 $('#preview-rendered').setAttribute('aria-pressed',String(previewMode==='rendered'));
 $('#preview-source').setAttribute('aria-pressed',String(previewMode==='source'));
 $('#file-preview').innerHTML=previewMode==='source'?'<pre tabindex="0">'+esc(previewText)+'</pre>':markdown(previewText);
}
$('#preview-rendered').onclick=()=>{previewMode='rendered';renderPreview();};
$('#preview-source').onclick=()=>{previewMode='source';renderPreview();};
$('#preview-download').onclick=async()=>{if(!previewItem)return;try{const text=await api('/api/artifact?job='+encodeURIComponent(previewItem.job)+'&milestone='+encodeURIComponent(previewItem.mid));const url=URL.createObjectURL(new Blob([text],{type:'text/markdown'}));const link=document.createElement('a');link.href=url;link.download=previewItem.name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){$('#file-preview').textContent=e.message;}};
$('#files').onclick=()=>{
 previewRequest++;previewItem=null;previewText='';$('#preview-tools').hidden=true;$('#file-preview').textContent='';
 const items=[];for(const j of state?.jobs||[])for(const [mid,m] of Object.entries(j.milestones)){if(m.state==='ACCEPTED'&&m.artifact){const spec=j.contract.milestones.find(s=>s.id===mid);items.push({job:j.id,mid,name:spec.filename});}}
 $('#file-list').innerHTML=items.length?items.map((f,i)=>'<button data-preview-index="'+i+'">'+esc(f.name)+'</button>').join(''):'<p>No checked files in this conversation yet.</p>';
 $('#file-list').onclick=async e=>{const b=e.target.closest('[data-preview-index]');if(!b)return;const item=items[Number(b.dataset.previewIndex)],request=++previewRequest;previewItem=null;$('#preview-tools').hidden=true;$('#file-preview').textContent='Loading file…';try{const text=await api('/api/artifact?job='+encodeURIComponent(item.job)+'&milestone='+encodeURIComponent(item.mid));if(request!==previewRequest)return;previewItem=item;previewText=text;previewMode='rendered';$('#preview-tools').hidden=false;renderPreview();}catch(error){if(request===previewRequest)$('#file-preview').textContent=error.message;}};
 $('#files-dialog').showModal();
};
$('#files-dialog').addEventListener('close',()=>{previewRequest++;});
